
package co.com.siscomputo.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Administacion", targetNamespace = "http://endpoint.siscomputo.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Administacion {


    /**
     * 
     * @param disopsicion
     * @return
     *     returns co.com.siscomputo.endpoint.DisposicionesEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarDisposicion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarDisposicion")
    @ResponseWrapper(localName = "insertarDisposicionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarDisposicionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarDisposicionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarDisposicionResponse")
    public DisposicionesEntity insertarDisposicion(
        @WebParam(name = "disopsicion", targetNamespace = "")
        DisposicionesEntity disopsicion);

    /**
     * 
     * @param metodo
     * @return
     *     returns co.com.siscomputo.endpoint.MetodoRecuperacionEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarMetodoRecuperacion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarMetodoRecuperacion")
    @ResponseWrapper(localName = "insertarMetodoRecuperacionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarMetodoRecuperacionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarMetodoRecuperacionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarMetodoRecuperacionResponse")
    public MetodoRecuperacionEntity insertarMetodoRecuperacion(
        @WebParam(name = "metodo", targetNamespace = "")
        MetodoRecuperacionEntity metodo);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaMetodoRecuperacion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaMetodoRecuperacion")
    @ResponseWrapper(localName = "listaMetodoRecuperacionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaMetodoRecuperacionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaMetodoRecuperacionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaMetodoRecuperacionResponse")
    public ObjetoRetornaEntity listaMetodoRecuperacion();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoControlDistribucionEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarTipoControlDistribucion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoControlDistribucion")
    @ResponseWrapper(localName = "actualizarTipoControlDistribucionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoControlDistribucionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarTipoControlDistribucionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarTipoControlDistribucionResponse")
    public TipoControlDistribucionEntity actualizarTipoControlDistribucion(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoControlDistribucionEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaElaborador", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaElaborador")
    @ResponseWrapper(localName = "listaElaboradorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaElaboradorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaElaboradorRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaElaboradorResponse")
    public ObjetoRetornaEntity listaElaborador();

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPlantilla", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPlantilla")
    @ResponseWrapper(localName = "listaPlantillaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPlantillaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaPlantillaRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaPlantillaResponse")
    public ObjetoRetornaEntity listaPlantilla();

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTiposAcceso", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTiposAcceso")
    @ResponseWrapper(localName = "listaTiposAccesoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTiposAccesoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaTiposAccesoRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaTiposAccesoResponse")
    public ObjetoRetornaEntity listaTiposAcceso();

    /**
     * 
     * @param disposicion
     * @return
     *     returns co.com.siscomputo.endpoint.DisposicionesEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarDisposicion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarDisposicion")
    @ResponseWrapper(localName = "actualizarDisposicionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarDisposicionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarDisposicionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarDisposicionResponse")
    public DisposicionesEntity actualizarDisposicion(
        @WebParam(name = "disposicion", targetNamespace = "")
        DisposicionesEntity disposicion);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDisposiciones", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaDisposiciones")
    @ResponseWrapper(localName = "listaDisposicionesResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaDisposicionesResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaDisposicionesRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaDisposicionesResponse")
    public ObjetoRetornaEntity listaDisposiciones();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.ElaboradorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarElaborador", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarElaborador")
    @ResponseWrapper(localName = "actualizarElaboradorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarElaboradorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarElaboradorRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarElaboradorResponse")
    public ElaboradorEntity actualizarElaborador(
        @WebParam(name = "objeto", targetNamespace = "")
        ElaboradorEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.ElaboradorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarElaborador", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarElaborador")
    @ResponseWrapper(localName = "insertarElaboradorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarElaboradorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarElaboradorRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarElaboradorResponse")
    public ElaboradorEntity insertarElaborador(
        @WebParam(name = "objeto", targetNamespace = "")
        ElaboradorEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.MetodoProteccionEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarMetodoProteccion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarMetodoProteccion")
    @ResponseWrapper(localName = "actualizarMetodoProteccionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarMetodoProteccionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarMetodoProteccionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarMetodoProteccionResponse")
    public MetodoProteccionEntity actualizarMetodoProteccion(
        @WebParam(name = "objeto", targetNamespace = "")
        MetodoProteccionEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaMetodoProteccion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaMetodoProteccion")
    @ResponseWrapper(localName = "listaMetodoProteccionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaMetodoProteccionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaMetodoProteccionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaMetodoProteccionResponse")
    public ObjetoRetornaEntity listaMetodoProteccion();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.MetodoProteccionEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarMetodoProteccion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarMetodoProteccion")
    @ResponseWrapper(localName = "insertarMetodoProteccionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarMetodoProteccionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarMetodoProteccionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarMetodoProteccionResponse")
    public MetodoProteccionEntity insertarMetodoProteccion(
        @WebParam(name = "objeto", targetNamespace = "")
        MetodoProteccionEntity objeto);

    /**
     * 
     * @param metodo
     * @return
     *     returns co.com.siscomputo.endpoint.MetodoRecuperacionEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarMetodoRecuperacion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarMetodoRecuperacion")
    @ResponseWrapper(localName = "actualizarMetodoRecuperacionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarMetodoRecuperacionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarMetodoRecuperacionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarMetodoRecuperacionResponse")
    public MetodoRecuperacionEntity actualizarMetodoRecuperacion(
        @WebParam(name = "metodo", targetNamespace = "")
        MetodoRecuperacionEntity metodo);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.PlantillaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarPlantilla", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarPlantilla")
    @ResponseWrapper(localName = "actualizarPlantillaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarPlantillaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarPlantillaRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarPlantillaResponse")
    public PlantillaEntity actualizarPlantilla(
        @WebParam(name = "objeto", targetNamespace = "")
        PlantillaEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.PlantillaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarPlantilla", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarPlantilla")
    @ResponseWrapper(localName = "insertarPlantillaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarPlantillaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarPlantillaRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarPlantillaResponse")
    public PlantillaEntity insertarPlantilla(
        @WebParam(name = "objeto", targetNamespace = "")
        PlantillaEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoAlmacenamientoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarTipoAlmacenamiento", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoAlmacenamiento")
    @ResponseWrapper(localName = "actualizarTipoAlmacenamientoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoAlmacenamientoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarTipoAlmacenamientoRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarTipoAlmacenamientoResponse")
    public TipoAlmacenamientoEntity actualizarTipoAlmacenamiento(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoAlmacenamientoEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoAlmacenamiento", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoAlmacenamiento")
    @ResponseWrapper(localName = "listaTipoAlmacenamientoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoAlmacenamientoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaTipoAlmacenamientoRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaTipoAlmacenamientoResponse")
    public ObjetoRetornaEntity listaTipoAlmacenamiento();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoAlmacenamientoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarTipoAlmacenamiento", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoAlmacenamiento")
    @ResponseWrapper(localName = "insertarTipoAlmacenamientoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoAlmacenamientoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarTipoAlmacenamientoRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarTipoAlmacenamientoResponse")
    public TipoAlmacenamientoEntity insertarTipoAlmacenamiento(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoAlmacenamientoEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoControlDistribucion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoControlDistribucion")
    @ResponseWrapper(localName = "listaTipoControlDistribucionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoControlDistribucionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaTipoControlDistribucionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaTipoControlDistribucionResponse")
    public ObjetoRetornaEntity listaTipoControlDistribucion();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoControlDistribucionEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarTipoControlDistribucion", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoControlDistribucion")
    @ResponseWrapper(localName = "insertarTipoControlDistribucionResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoControlDistribucionResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarTipoControlDistribucionRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarTipoControlDistribucionResponse")
    public TipoControlDistribucionEntity insertarTipoControlDistribucion(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoControlDistribucionEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TiposAccesoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarTiposAcceso", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTiposAcceso")
    @ResponseWrapper(localName = "actualizarTiposAccesoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTiposAccesoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarTiposAccesoRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarTiposAccesoResponse")
    public TiposAccesoEntity actualizarTiposAcceso(
        @WebParam(name = "objeto", targetNamespace = "")
        TiposAccesoEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TiposAccesoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarTiposAcceso", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTiposAcceso")
    @ResponseWrapper(localName = "insertarTiposAccesoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTiposAccesoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarTiposAccesoRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarTiposAccesoResponse")
    public TiposAccesoEntity insertarTiposAcceso(
        @WebParam(name = "objeto", targetNamespace = "")
        TiposAccesoEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.ModificadorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarModificador", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarModificador")
    @ResponseWrapper(localName = "insertarModificadorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarModificadorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/insertarModificadorRequest", output = "http://endpoint.siscomputo.com.co/Administacion/insertarModificadorResponse")
    public ModificadorEntity insertarModificador(
        @WebParam(name = "objeto", targetNamespace = "")
        ModificadorEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.ModificadorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarModificador", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarModificador")
    @ResponseWrapper(localName = "actualizarModificadorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarModificadorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/actualizarModificadorRequest", output = "http://endpoint.siscomputo.com.co/Administacion/actualizarModificadorResponse")
    public ModificadorEntity actualizarModificador(
        @WebParam(name = "objeto", targetNamespace = "")
        ModificadorEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaModificador", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaModificador")
    @ResponseWrapper(localName = "listaModificadorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaModificadorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/listaModificadorRequest", output = "http://endpoint.siscomputo.com.co/Administacion/listaModificadorResponse")
    public ObjetoRetornaEntity listaModificador();

    /**
     * 
     * @param onjeto
     * @return
     *     returns co.com.siscomputo.endpoint.ModificadorEntity
     */
    @WebMethod(operationName = "ModificadorPorId")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ModificadorPorId", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ModificadorPorId")
    @ResponseWrapper(localName = "ModificadorPorIdResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ModificadorPorIdResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/ModificadorPorIdRequest", output = "http://endpoint.siscomputo.com.co/Administacion/ModificadorPorIdResponse")
    public ModificadorEntity modificadorPorId(
        @WebParam(name = "onjeto", targetNamespace = "")
        int onjeto);

    /**
     * 
     * @param idDepto
     * @return
     *     returns co.com.siscomputo.endpoint.ElaboradorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "elaboradorPorId", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ElaboradorPorId")
    @ResponseWrapper(localName = "elaboradorPorIdResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ElaboradorPorIdResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Administacion/elaboradorPorIdRequest", output = "http://endpoint.siscomputo.com.co/Administacion/elaboradorPorIdResponse")
    public ElaboradorEntity elaboradorPorId(
        @WebParam(name = "idDepto", targetNamespace = "")
        int idDepto);

}
