
package co.com.siscomputo.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionDocumental", targetNamespace = "http://endpoint.siscomputo.com.co/", wsdlLocation = "http://localhost:8084/ISODOCWS/GestionDocumental?wsdl")
public class GestionDocumental_Service
    extends Service
{

    private final static URL GESTIONDOCUMENTAL_WSDL_LOCATION;
    private final static WebServiceException GESTIONDOCUMENTAL_EXCEPTION;
    private final static QName GESTIONDOCUMENTAL_QNAME = new QName("http://endpoint.siscomputo.com.co/", "GestionDocumental");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/ISODOCWS/GestionDocumental?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONDOCUMENTAL_WSDL_LOCATION = url;
        GESTIONDOCUMENTAL_EXCEPTION = e;
    }

    public GestionDocumental_Service() {
        super(__getWsdlLocation(), GESTIONDOCUMENTAL_QNAME);
    }

    public GestionDocumental_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONDOCUMENTAL_QNAME, features);
    }

    public GestionDocumental_Service(URL wsdlLocation) {
        super(wsdlLocation, GESTIONDOCUMENTAL_QNAME);
    }

    public GestionDocumental_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONDOCUMENTAL_QNAME, features);
    }

    public GestionDocumental_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionDocumental_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionDocumental
     */
    @WebEndpoint(name = "GestionDocumentalPort")
    public GestionDocumental getGestionDocumentalPort() {
        return super.getPort(new QName("http://endpoint.siscomputo.com.co/", "GestionDocumentalPort"), GestionDocumental.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionDocumental
     */
    @WebEndpoint(name = "GestionDocumentalPort")
    public GestionDocumental getGestionDocumentalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.siscomputo.com.co/", "GestionDocumentalPort"), GestionDocumental.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONDOCUMENTAL_EXCEPTION!= null) {
            throw GESTIONDOCUMENTAL_EXCEPTION;
        }
        return GESTIONDOCUMENTAL_WSDL_LOCATION;
    }

}
