
package co.com.siscomputo.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Proveedores", targetNamespace = "http://endpoint.siscomputo.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Proveedores {


    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoCuentaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarTipoCuenta", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoCuenta")
    @ResponseWrapper(localName = "actualizarTipoCuentaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoCuentaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarTipoCuentaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarTipoCuentaResponse")
    public TipoCuentaEntity actualizarTipoCuenta(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoCuentaEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoCuentaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarTipoCuenta", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoCuenta")
    @ResponseWrapper(localName = "insertarTipoCuentaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoCuentaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoCuentaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoCuentaResponse")
    public TipoCuentaEntity insertarTipoCuenta(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoCuentaEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoDocumentoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarTipoDocumento", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoDocumento")
    @ResponseWrapper(localName = "actualizarTipoDocumentoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoDocumentoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarTipoDocumentoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarTipoDocumentoResponse")
    public TipoDocumentoEntity actualizarTipoDocumento(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoDocumentoEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoDocumentoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarTipoDocumento", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoDocumento")
    @ResponseWrapper(localName = "insertarTipoDocumentoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoDocumentoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoDocumentoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoDocumentoResponse")
    public TipoDocumentoEntity insertarTipoDocumento(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoDocumentoEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoProveedorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarTipoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoProveedor")
    @ResponseWrapper(localName = "actualizarTipoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarTipoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarTipoProveedorResponse")
    public TipoProveedorEntity actualizarTipoProveedor(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoProveedorEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoProveedor")
    @ResponseWrapper(localName = "listaTipoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoProveedorResponse")
    public ObjetoRetornaEntity listaTipoProveedor();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoProveedorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarTipoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoProveedor")
    @ResponseWrapper(localName = "insertarTipoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoProveedorResponse")
    public TipoProveedorEntity insertarTipoProveedor(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoProveedorEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoTributarioEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarTipoTributario", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoTributario")
    @ResponseWrapper(localName = "actualizarTipoTributarioResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarTipoTributarioResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarTipoTributarioRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarTipoTributarioResponse")
    public TipoTributarioEntity actualizarTipoTributario(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoTributarioEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoTributario", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoTributario")
    @ResponseWrapper(localName = "listaTipoTributarioResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoTributarioResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoTributarioRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoTributarioResponse")
    public ObjetoRetornaEntity listaTipoTributario();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.TipoTributarioEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarTipoTributario", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoTributario")
    @ResponseWrapper(localName = "insertarTipoTributarioResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoTributarioResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoTributarioRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoTributarioResponse")
    public TipoTributarioEntity insertarTipoTributario(
        @WebParam(name = "objeto", targetNamespace = "")
        TipoTributarioEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.LineaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarLinea", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarLinea")
    @ResponseWrapper(localName = "actualizarLineaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarLineaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarLineaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarLineaResponse")
    public LineaEntity actualizarLinea(
        @WebParam(name = "objeto", targetNamespace = "")
        LineaEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaLinea", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaLinea")
    @ResponseWrapper(localName = "listaLineaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaLineaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaLineaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaLineaResponse")
    public ObjetoRetornaEntity listaLinea();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.LineaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarLinea", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarLinea")
    @ResponseWrapper(localName = "insertarLineaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarLineaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarLineaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarLineaResponse")
    public LineaEntity insertarLinea(
        @WebParam(name = "objeto", targetNamespace = "")
        LineaEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoCuenta", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoCuenta")
    @ResponseWrapper(localName = "listaTipoCuentaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoCuentaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoCuentaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoCuentaResponse")
    public ObjetoRetornaEntity listaTipoCuenta();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.CuentasProveedoresEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarCuentasProveedores", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarCuentasProveedores")
    @ResponseWrapper(localName = "actualizarCuentasProveedoresResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarCuentasProveedoresResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarCuentasProveedoresRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarCuentasProveedoresResponse")
    public CuentasProveedoresEntity actualizarCuentasProveedores(
        @WebParam(name = "objeto", targetNamespace = "")
        CuentasProveedoresEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCuentasProveedores", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaCuentasProveedores")
    @ResponseWrapper(localName = "listaCuentasProveedoresResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaCuentasProveedoresResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaCuentasProveedoresRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaCuentasProveedoresResponse")
    public ObjetoRetornaEntity listaCuentasProveedores();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.CuentasProveedoresEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarCuentasProveedores", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarCuentasProveedores")
    @ResponseWrapper(localName = "insertarCuentasProveedoresResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarCuentasProveedoresResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarCuentasProveedoresRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarCuentasProveedoresResponse")
    public CuentasProveedoresEntity insertarCuentasProveedores(
        @WebParam(name = "objeto", targetNamespace = "")
        CuentasProveedoresEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.EstadoProveedorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarEstadoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarEstadoProveedor")
    @ResponseWrapper(localName = "actualizarEstadoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarEstadoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarEstadoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarEstadoProveedorResponse")
    public EstadoProveedorEntity actualizarEstadoProveedor(
        @WebParam(name = "objeto", targetNamespace = "")
        EstadoProveedorEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaEstadoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaEstadoProveedor")
    @ResponseWrapper(localName = "listaEstadoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaEstadoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaEstadoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaEstadoProveedorResponse")
    public ObjetoRetornaEntity listaEstadoProveedor();

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.EstadoProveedorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarEstadoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarEstadoProveedor")
    @ResponseWrapper(localName = "insertarEstadoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarEstadoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarEstadoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarEstadoProveedorResponse")
    public EstadoProveedorEntity insertarEstadoProveedor(
        @WebParam(name = "objeto", targetNamespace = "")
        EstadoProveedorEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoDocumento", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoDocumento")
    @ResponseWrapper(localName = "listaTipoDocumentoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoDocumentoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoDocumentoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoDocumentoResponse")
    public ObjetoRetornaEntity listaTipoDocumento();

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaProveedor")
    @ResponseWrapper(localName = "listaProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaProveedorResponse")
    public ObjetoRetornaEntity listaProveedor();

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaFormaPago", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaFormaPago")
    @ResponseWrapper(localName = "listaFormaPagoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaFormaPagoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaFormaPagoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaFormaPagoResponse")
    public ObjetoRetornaEntity listaFormaPago();

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTipoMoneda", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoMoneda")
    @ResponseWrapper(localName = "listaTipoMonedaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaTipoMonedaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoMonedaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaTipoMonedaResponse")
    public ObjetoRetornaEntity listaTipoMoneda();

    /**
     * 
     * @param contrato
     * @return
     *     returns co.com.siscomputo.endpoint.ContratosEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarContrato", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarContrato")
    @ResponseWrapper(localName = "insertarContratoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarContratoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarContratoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarContratoResponse")
    public ContratosEntity insertarContrato(
        @WebParam(name = "contrato", targetNamespace = "")
        ContratosEntity contrato);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaContratos", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaContratos")
    @ResponseWrapper(localName = "listaContratosResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaContratosResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaContratosRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaContratosResponse")
    public ObjetoRetornaEntity listaContratos();

    /**
     * 
     * @param polizaEntity
     * @return
     *     returns co.com.siscomputo.endpoint.PolizasEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarPoliza", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarPoliza")
    @ResponseWrapper(localName = "insertarPolizaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarPolizaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarPolizaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarPolizaResponse")
    public PolizasEntity insertarPoliza(
        @WebParam(name = "PolizaEntity", targetNamespace = "")
        PolizasEntity polizaEntity);

    /**
     * 
     * @param polizaEntity
     * @return
     *     returns co.com.siscomputo.endpoint.PolizasEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarPoliza", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarPoliza")
    @ResponseWrapper(localName = "actualizarPolizaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarPolizaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarPolizaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarPolizaResponse")
    public PolizasEntity actualizarPoliza(
        @WebParam(name = "PolizaEntity", targetNamespace = "")
        PolizasEntity polizaEntity);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPoliza", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPoliza")
    @ResponseWrapper(localName = "listaPolizaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPolizaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaPolizaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaPolizaResponse")
    public ObjetoRetornaEntity listaPoliza();

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCertificado", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaCertificado")
    @ResponseWrapper(localName = "listaCertificadoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaCertificadoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaCertificadoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaCertificadoResponse")
    public ObjetoRetornaEntity listaCertificado();

    /**
     * 
     * @param formaPago
     * @return
     *     returns co.com.siscomputo.endpoint.FormasPagoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarFormaPago", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarFormaPago")
    @ResponseWrapper(localName = "insertarFormaPagoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarFormaPagoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarFormaPagoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarFormaPagoResponse")
    public FormasPagoEntity insertarFormaPago(
        @WebParam(name = "formaPago", targetNamespace = "")
        FormasPagoEntity formaPago);

    /**
     * 
     * @param formaPago
     * @return
     *     returns co.com.siscomputo.endpoint.FormasPagoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarFormaPago", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarFormaPago")
    @ResponseWrapper(localName = "actualizarFormaPagoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarFormaPagoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarFormaPagoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarFormaPagoResponse")
    public FormasPagoEntity actualizarFormaPago(
        @WebParam(name = "formaPago", targetNamespace = "")
        FormasPagoEntity formaPago);

    /**
     * 
     * @param proveedor
     * @return
     *     returns co.com.siscomputo.endpoint.ProveedoresEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarProveedor")
    @ResponseWrapper(localName = "insertarProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarProveedorResponse")
    public ProveedoresEntity insertarProveedor(
        @WebParam(name = "proveedor", targetNamespace = "")
        ProveedoresEntity proveedor);

    /**
     * 
     * @param proveedor
     * @return
     *     returns co.com.siscomputo.endpoint.ProveedoresEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarProveedor")
    @ResponseWrapper(localName = "actualizarProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarProveedorResponse")
    public ProveedoresEntity actualizarProveedor(
        @WebParam(name = "proveedor", targetNamespace = "")
        ProveedoresEntity proveedor);

    /**
     * 
     * @param tipoMoneda
     * @return
     *     returns co.com.siscomputo.endpoint.TipoMonedaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarTipoMoneda", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoMoneda")
    @ResponseWrapper(localName = "insertarTipoMonedaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarTipoMonedaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoMonedaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarTipoMonedaResponse")
    public TipoMonedaEntity insertarTipoMoneda(
        @WebParam(name = "tipoMoneda", targetNamespace = "")
        TipoMonedaEntity tipoMoneda);

    /**
     * 
     * @param tipoMoneda
     * @return
     *     returns co.com.siscomputo.endpoint.TipoMonedaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarMoneda", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarMoneda")
    @ResponseWrapper(localName = "actualizarMonedaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarMonedaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarMonedaRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarMonedaResponse")
    public TipoMonedaEntity actualizarMoneda(
        @WebParam(name = "tipoMoneda", targetNamespace = "")
        TipoMonedaEntity tipoMoneda);

    /**
     * 
     * @param contrato
     * @return
     *     returns co.com.siscomputo.endpoint.ContratosEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarContrato", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarContrato")
    @ResponseWrapper(localName = "actualizarContratoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarContratoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarContratoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarContratoResponse")
    public ContratosEntity actualizarContrato(
        @WebParam(name = "contrato", targetNamespace = "")
        ContratosEntity contrato);

    /**
     * 
     * @param certificadoEntity
     * @return
     *     returns co.com.siscomputo.endpoint.CertificadoCalidadEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarCertificado", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarCertificado")
    @ResponseWrapper(localName = "insertarCertificadoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarCertificadoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarCertificadoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarCertificadoResponse")
    public CertificadoCalidadEntity insertarCertificado(
        @WebParam(name = "CertificadoEntity", targetNamespace = "")
        CertificadoCalidadEntity certificadoEntity);

    /**
     * 
     * @param certificadoEntity
     * @return
     *     returns co.com.siscomputo.endpoint.CertificadoCalidadEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarCertificado", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarCertificado")
    @ResponseWrapper(localName = "actualizarCertificadoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarCertificadoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarCertificadoRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarCertificadoResponse")
    public CertificadoCalidadEntity actualizarCertificado(
        @WebParam(name = "CertificadoEntity", targetNamespace = "")
        CertificadoCalidadEntity certificadoEntity);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.AnexoProveedorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarAnexoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarAnexoProveedor")
    @ResponseWrapper(localName = "insertarAnexoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarAnexoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/insertarAnexoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/insertarAnexoProveedorResponse")
    public AnexoProveedorEntity insertarAnexoProveedor(
        @WebParam(name = "objeto", targetNamespace = "")
        AnexoProveedorEntity objeto);

    /**
     * 
     * @param objeto
     * @return
     *     returns co.com.siscomputo.endpoint.AnexoProveedorEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarAnexoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarAnexoProveedor")
    @ResponseWrapper(localName = "actualizarAnexoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarAnexoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/actualizarAnexoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/actualizarAnexoProveedorResponse")
    public AnexoProveedorEntity actualizarAnexoProveedor(
        @WebParam(name = "objeto", targetNamespace = "")
        AnexoProveedorEntity objeto);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaAnexoProveedor", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaAnexoProveedor")
    @ResponseWrapper(localName = "listaAnexoProveedorResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaAnexoProveedorResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Proveedores/listaAnexoProveedorRequest", output = "http://endpoint.siscomputo.com.co/Proveedores/listaAnexoProveedorResponse")
    public ObjetoRetornaEntity listaAnexoProveedor();

}
