
package co.com.siscomputo.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Proveedores", targetNamespace = "http://endpoint.siscomputo.com.co/", wsdlLocation = "http://localhost:8084/ISODOCWS/Proveedores?wsdl")
public class Proveedores_Service
    extends Service
{

    private final static URL PROVEEDORES_WSDL_LOCATION;
    private final static WebServiceException PROVEEDORES_EXCEPTION;
    private final static QName PROVEEDORES_QNAME = new QName("http://endpoint.siscomputo.com.co/", "Proveedores");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/ISODOCWS/Proveedores?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROVEEDORES_WSDL_LOCATION = url;
        PROVEEDORES_EXCEPTION = e;
    }

    public Proveedores_Service() {
        super(__getWsdlLocation(), PROVEEDORES_QNAME);
    }

    public Proveedores_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVEEDORES_QNAME, features);
    }

    public Proveedores_Service(URL wsdlLocation) {
        super(wsdlLocation, PROVEEDORES_QNAME);
    }

    public Proveedores_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVEEDORES_QNAME, features);
    }

    public Proveedores_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Proveedores_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Proveedores
     */
    @WebEndpoint(name = "ProveedoresPort")
    public Proveedores getProveedoresPort() {
        return super.getPort(new QName("http://endpoint.siscomputo.com.co/", "ProveedoresPort"), Proveedores.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Proveedores
     */
    @WebEndpoint(name = "ProveedoresPort")
    public Proveedores getProveedoresPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.siscomputo.com.co/", "ProveedoresPort"), Proveedores.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVEEDORES_EXCEPTION!= null) {
            throw PROVEEDORES_EXCEPTION;
        }
        return PROVEEDORES_WSDL_LOCATION;
    }

}
