
package co.com.siscomputo.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Usuario", targetNamespace = "http://endpoint.siscomputo.com.co/", wsdlLocation = "http://localhost:8084/ISODOCWS/Usuario?wsdl")
public class Usuario_Service
    extends Service
{

    private final static URL USUARIO_WSDL_LOCATION;
    private final static WebServiceException USUARIO_EXCEPTION;
    private final static QName USUARIO_QNAME = new QName("http://endpoint.siscomputo.com.co/", "Usuario");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/ISODOCWS/Usuario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIO_WSDL_LOCATION = url;
        USUARIO_EXCEPTION = e;
    }

    public Usuario_Service() {
        super(__getWsdlLocation(), USUARIO_QNAME);
    }

    public Usuario_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIO_QNAME, features);
    }

    public Usuario_Service(URL wsdlLocation) {
        super(wsdlLocation, USUARIO_QNAME);
    }

    public Usuario_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIO_QNAME, features);
    }

    public Usuario_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Usuario_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Usuario
     */
    @WebEndpoint(name = "UsuarioPort")
    public Usuario getUsuarioPort() {
        return super.getPort(new QName("http://endpoint.siscomputo.com.co/", "UsuarioPort"), Usuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Usuario
     */
    @WebEndpoint(name = "UsuarioPort")
    public Usuario getUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.siscomputo.com.co/", "UsuarioPort"), Usuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIO_EXCEPTION!= null) {
            throw USUARIO_EXCEPTION;
        }
        return USUARIO_WSDL_LOCATION;
    }

}
