
package co.com.siscomputo.endpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Usuario", targetNamespace = "http://endpoint.siscomputo.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Usuario {


    /**
     * 
     * @param pass
     * @param nombre
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoLogin
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.LoginResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/loginRequest", output = "http://endpoint.siscomputo.com.co/Usuario/loginResponse")
    public ObjetoLogin login(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param area
     * @return
     *     returns co.com.siscomputo.endpoint.AreaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarArea", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarArea")
    @ResponseWrapper(localName = "insertarAreaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarAreaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/insertarAreaRequest", output = "http://endpoint.siscomputo.com.co/Usuario/insertarAreaResponse")
    public AreaEntity insertarArea(
        @WebParam(name = "area", targetNamespace = "")
        AreaEntity area);

    /**
     * 
     * @param area
     * @return
     *     returns co.com.siscomputo.endpoint.AreaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarArea", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarArea")
    @ResponseWrapper(localName = "actualizarAreaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarAreaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizarAreaRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizarAreaResponse")
    public AreaEntity actualizarArea(
        @WebParam(name = "area", targetNamespace = "")
        AreaEntity area);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaAreas", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaAreas")
    @ResponseWrapper(localName = "listaAreasResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaAreasResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaAreasRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaAreasResponse")
    public ObjetoRetornaEntity listaAreas();

    /**
     * 
     * @param sede
     * @return
     *     returns co.com.siscomputo.endpoint.SedeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sedePorId", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.SedePorId")
    @ResponseWrapper(localName = "sedePorIdResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.SedePorIdResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/sedePorIdRequest", output = "http://endpoint.siscomputo.com.co/Usuario/sedePorIdResponse")
    public SedeEntity sedePorId(
        @WebParam(name = "sede", targetNamespace = "")
        int sede);

    /**
     * 
     * @param empresa
     * @return
     *     returns co.com.siscomputo.endpoint.EmpresaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresarEmpresa", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresarEmpresa")
    @ResponseWrapper(localName = "ingresarEmpresaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresarEmpresaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/ingresarEmpresaRequest", output = "http://endpoint.siscomputo.com.co/Usuario/ingresarEmpresaResponse")
    public EmpresaEntity ingresarEmpresa(
        @WebParam(name = "empresa", targetNamespace = "")
        EmpresaEntity empresa);

    /**
     * 
     * @param pais
     * @return
     *     returns co.com.siscomputo.endpoint.PaisEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarPais", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarPais")
    @ResponseWrapper(localName = "insertarPaisResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarPaisResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/insertarPaisRequest", output = "http://endpoint.siscomputo.com.co/Usuario/insertarPaisResponse")
    public PaisEntity insertarPais(
        @WebParam(name = "pais", targetNamespace = "")
        PaisEntity pais);

    /**
     * 
     * @param pais
     * @return
     *     returns co.com.siscomputo.endpoint.PaisEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarPais", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarPais")
    @ResponseWrapper(localName = "actualizarPaisResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarPaisResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizarPaisRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizarPaisResponse")
    public PaisEntity actualizarPais(
        @WebParam(name = "pais", targetNamespace = "")
        PaisEntity pais);

    /**
     * 
     * @param departamento
     * @return
     *     returns co.com.siscomputo.endpoint.DepartamentoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarDepartameno", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarDepartameno")
    @ResponseWrapper(localName = "insertarDepartamenoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarDepartamenoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/insertarDepartamenoRequest", output = "http://endpoint.siscomputo.com.co/Usuario/insertarDepartamenoResponse")
    public DepartamentoEntity insertarDepartameno(
        @WebParam(name = "departamento", targetNamespace = "")
        DepartamentoEntity departamento);

    /**
     * 
     * @param departamento
     * @return
     *     returns co.com.siscomputo.endpoint.DepartamentoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarDepartameno", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarDepartameno")
    @ResponseWrapper(localName = "actualizarDepartamenoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarDepartamenoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizarDepartamenoRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizarDepartamenoResponse")
    public DepartamentoEntity actualizarDepartameno(
        @WebParam(name = "departamento", targetNamespace = "")
        DepartamentoEntity departamento);

    /**
     * 
     * @param empresa
     * @return
     *     returns co.com.siscomputo.endpoint.EmpresaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarEmpresa", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarEmpresa")
    @ResponseWrapper(localName = "actualizarEmpresaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarEmpresaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizarEmpresaRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizarEmpresaResponse")
    public EmpresaEntity actualizarEmpresa(
        @WebParam(name = "empresa", targetNamespace = "")
        EmpresaEntity empresa);

    /**
     * 
     * @param usuario
     * @return
     *     returns co.com.siscomputo.endpoint.UsuarioEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarUsuario", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarUsuario")
    @ResponseWrapper(localName = "actualizarUsuarioResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarUsuarioResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizarUsuarioRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizarUsuarioResponse")
    public UsuarioEntity actualizarUsuario(
        @WebParam(name = "Usuario", targetNamespace = "")
        UsuarioEntity usuario);

    /**
     * 
     * @param rol
     * @return
     *     returns co.com.siscomputo.endpoint.RolesEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresarRol", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresarRol")
    @ResponseWrapper(localName = "ingresarRolResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresarRolResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/ingresarRolRequest", output = "http://endpoint.siscomputo.com.co/Usuario/ingresarRolResponse")
    public RolesEntity ingresarRol(
        @WebParam(name = "rol", targetNamespace = "")
        RolesEntity rol);

    /**
     * 
     * @param rol
     * @return
     *     returns co.com.siscomputo.endpoint.RolesEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarRol", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarRol")
    @ResponseWrapper(localName = "actualizarRolResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarRolResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizarRolRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizarRolResponse")
    public RolesEntity actualizarRol(
        @WebParam(name = "rol", targetNamespace = "")
        RolesEntity rol);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaRoles", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaRoles")
    @ResponseWrapper(localName = "listaRolesResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaRolesResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaRolesRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaRolesResponse")
    public ObjetoRetornaEntity listaRoles();

    /**
     * 
     * @param sede
     * @return
     *     returns co.com.siscomputo.endpoint.SedeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresaSede", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresaSede")
    @ResponseWrapper(localName = "ingresaSedeResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresaSedeResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/ingresaSedeRequest", output = "http://endpoint.siscomputo.com.co/Usuario/ingresaSedeResponse")
    public SedeEntity ingresaSede(
        @WebParam(name = "sede", targetNamespace = "")
        SedeEntity sede);

    /**
     * 
     * @param sede
     * @return
     *     returns co.com.siscomputo.endpoint.SedeEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaSede", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizaSede")
    @ResponseWrapper(localName = "actualizaSedeResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizaSedeResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizaSedeRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizaSedeResponse")
    public SedeEntity actualizaSede(
        @WebParam(name = "sede", targetNamespace = "")
        SedeEntity sede);

    /**
     * 
     * @param usuario
     * @return
     *     returns co.com.siscomputo.endpoint.UsuarioEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresarUsuario", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresarUsuario")
    @ResponseWrapper(localName = "ingresarUsuarioResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresarUsuarioResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/ingresarUsuarioRequest", output = "http://endpoint.siscomputo.com.co/Usuario/ingresarUsuarioResponse")
    public UsuarioEntity ingresarUsuario(
        @WebParam(name = "Usuario", targetNamespace = "")
        UsuarioEntity usuario);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaUsuarios", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaUsuarios")
    @ResponseWrapper(localName = "listaUsuariosResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaUsuariosResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaUsuariosRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaUsuariosResponse")
    public ObjetoRetornaEntity listaUsuarios();

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaSede", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaSede")
    @ResponseWrapper(localName = "listaSedeResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaSedeResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaSedeRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaSedeResponse")
    public ObjetoRetornaEntity listaSede();

    /**
     * 
     * @param idUsuario
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPermisos", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPermisos")
    @ResponseWrapper(localName = "listaPermisosResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPermisosResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaPermisosRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaPermisosResponse")
    public ObjetoRetornaEntity listaPermisos(
        @WebParam(name = "id_usuario", targetNamespace = "")
        int idUsuario);

    /**
     * 
     * @param idUsuario
     * @return
     *     returns co.com.siscomputo.endpoint.UsuarioEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "usuarioPorId", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.UsuarioPorId")
    @ResponseWrapper(localName = "usuarioPorIdResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.UsuarioPorIdResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/usuarioPorIdRequest", output = "http://endpoint.siscomputo.com.co/Usuario/usuarioPorIdResponse")
    public UsuarioEntity usuarioPorId(
        @WebParam(name = "idUsuario", targetNamespace = "")
        int idUsuario);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPais", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPais")
    @ResponseWrapper(localName = "listaPaisResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPaisResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaPaisRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaPaisResponse")
    public ObjetoRetornaEntity listaPais();

    /**
     * 
     * @param idUsuario
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaModulos", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaModulos")
    @ResponseWrapper(localName = "listaModulosResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaModulosResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaModulosRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaModulosResponse")
    public ObjetoRetornaEntity listaModulos(
        @WebParam(name = "id_usuario", targetNamespace = "")
        int idUsuario);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaEmpresa", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaEmpresa")
    @ResponseWrapper(localName = "listaEmpresaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaEmpresaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaEmpresaRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaEmpresaResponse")
    public ObjetoRetornaEntity listaEmpresa();

    /**
     * 
     * @param ciudad
     * @return
     *     returns co.com.siscomputo.endpoint.CiudadEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarCiudad", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarCiudad")
    @ResponseWrapper(localName = "actualizarCiudadResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizarCiudadResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizarCiudadRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizarCiudadResponse")
    public CiudadEntity actualizarCiudad(
        @WebParam(name = "ciudad", targetNamespace = "")
        CiudadEntity ciudad);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaSedeEmpresa", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaSedeEmpresa")
    @ResponseWrapper(localName = "listaSedeEmpresaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaSedeEmpresaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaSedeEmpresaRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaSedeEmpresaResponse")
    public ObjetoRetornaEntity listaSedeEmpresa();

    /**
     * 
     * @return
     *     returns java.util.List<co.com.siscomputo.endpoint.ListaAsignaPermisosModulo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPermisosDisponibles", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPermisosDisponibles")
    @ResponseWrapper(localName = "listaPermisosDisponiblesResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPermisosDisponiblesResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaPermisosDisponiblesRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaPermisosDisponiblesResponse")
    public List<ListaAsignaPermisosModulo> listaPermisosDisponibles();

    /**
     * 
     * @param idUsuario
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaPermisosFiltrados", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPermisosFiltrados")
    @ResponseWrapper(localName = "listaPermisosFiltradosResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaPermisosFiltradosResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaPermisosFiltradosRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaPermisosFiltradosResponse")
    public ObjetoRetornaEntity listaPermisosFiltrados(
        @WebParam(name = "idUsuario", targetNamespace = "")
        int idUsuario);

    /**
     * 
     * @param idUsuario
     * @return
     *     returns java.util.List<co.com.siscomputo.endpoint.MenuModuloEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "menuDatosporUsuario", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.MenuDatosporUsuario")
    @ResponseWrapper(localName = "menuDatosporUsuarioResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.MenuDatosporUsuarioResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/menuDatosporUsuarioRequest", output = "http://endpoint.siscomputo.com.co/Usuario/menuDatosporUsuarioResponse")
    public List<MenuModuloEntity> menuDatosporUsuario(
        @WebParam(name = "idUsuario", targetNamespace = "")
        int idUsuario);

    /**
     * 
     * @param sedee
     * @return
     *     returns co.com.siscomputo.endpoint.SedeEmpresaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaSedeEmpresa", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizaSedeEmpresa")
    @ResponseWrapper(localName = "actualizaSedeEmpresaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ActualizaSedeEmpresaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/actualizaSedeEmpresaRequest", output = "http://endpoint.siscomputo.com.co/Usuario/actualizaSedeEmpresaResponse")
    public SedeEmpresaEntity actualizaSedeEmpresa(
        @WebParam(name = "sedee", targetNamespace = "")
        SedeEmpresaEntity sedee);

    /**
     * 
     * @param idPais
     * @return
     *     returns co.com.siscomputo.endpoint.PaisEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "paisPorId", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.PaisPorId")
    @ResponseWrapper(localName = "paisPorIdResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.PaisPorIdResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/paisPorIdRequest", output = "http://endpoint.siscomputo.com.co/Usuario/paisPorIdResponse")
    public PaisEntity paisPorId(
        @WebParam(name = "idPais", targetNamespace = "")
        int idPais);

    /**
     * 
     * @param sedee
     * @return
     *     returns co.com.siscomputo.endpoint.SedeEmpresaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresaSedeEmpresa", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresaSedeEmpresa")
    @ResponseWrapper(localName = "ingresaSedeEmpresaResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.IngresaSedeEmpresaResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/ingresaSedeEmpresaRequest", output = "http://endpoint.siscomputo.com.co/Usuario/ingresaSedeEmpresaResponse")
    public SedeEmpresaEntity ingresaSedeEmpresa(
        @WebParam(name = "sedee", targetNamespace = "")
        SedeEmpresaEntity sedee);

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaDepartameno", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaDepartameno")
    @ResponseWrapper(localName = "listaDepartamenoResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaDepartamenoResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaDepartamenoRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaDepartamenoResponse")
    public ObjetoRetornaEntity listaDepartameno();

    /**
     * 
     * @return
     *     returns co.com.siscomputo.endpoint.ObjetoRetornaEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCiudades", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaCiudades")
    @ResponseWrapper(localName = "listaCiudadesResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.ListaCiudadesResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/listaCiudadesRequest", output = "http://endpoint.siscomputo.com.co/Usuario/listaCiudadesResponse")
    public ObjetoRetornaEntity listaCiudades();

    /**
     * 
     * @param ciudad
     * @return
     *     returns co.com.siscomputo.endpoint.CiudadEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertarCiudad", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarCiudad")
    @ResponseWrapper(localName = "insertarCiudadResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.InsertarCiudadResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/insertarCiudadRequest", output = "http://endpoint.siscomputo.com.co/Usuario/insertarCiudadResponse")
    public CiudadEntity insertarCiudad(
        @WebParam(name = "ciudad", targetNamespace = "")
        CiudadEntity ciudad);

    /**
     * 
     * @param idDepto
     * @return
     *     returns co.com.siscomputo.endpoint.DepartamentoEntity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deptoPorId", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.DeptoPorId")
    @ResponseWrapper(localName = "deptoPorIdResponse", targetNamespace = "http://endpoint.siscomputo.com.co/", className = "co.com.siscomputo.endpoint.DeptoPorIdResponse")
    @Action(input = "http://endpoint.siscomputo.com.co/Usuario/deptoPorIdRequest", output = "http://endpoint.siscomputo.com.co/Usuario/deptoPorIdResponse")
    public DepartamentoEntity deptoPorId(
        @WebParam(name = "idDepto", targetNamespace = "")
        int idDepto);

}
